language: groovy
jdk: oraclejdk8
sudo: false
env:
  global:
  - secure: eI+SoVNnCyhMPLuOPhE786C7EN+Mt1GO+b5jBZVB+r5Pjhyq9D9bQznBaxMvf6QQJ+VIuCcvPGsUpePxFQbr16n8qrxmF7GjW5TYM72+PxlxQQi+jtzwbnGPpjePC9hlCucoexvz/V6eomXtJsRLsibdnBB/9VbKNZ5sB1td/1Y=
  - secure: FmeVGzwlHzsITwWQZqrZh7EDs+z6m0Y/O9HuRN7Qb+1t3YmDPm5MPEqppm8laE/dkR36kHxcIBMOJ8Uen//84gXmD4jxXM11JAFjQLPcrwKVFFybUR24J2fqiKuOCedhSzRNsqM4Jw8M6g6z3PjoVsB4a12AeWXUflIfyLgAlk0=
script:
- "./gradlew clean assemble --stacktrace"
after_success:
- "./travis-publish.sh"
